//! The files that make an export a crate you can run, rather than a folder of
//! components you still have to wire up.
//!
//! `main.rs` opens a window on the first screen and `Cargo.toml` pins the same
//! library and gpui this repo builds. Nothing here imports Tailor.
//!
//! `theme.rs` is the provider's — a theme is written entirely in the library's
//! own vocabulary — so it comes from
//! [`Generator::theme_rs`](crate::Generator::theme_rs).

use std::collections::BTreeMap;
use tailor_model::{DocKind, Project};

use crate::file::Generated;
use crate::rust::{comment, Source};

/// `main.rs` — a window on the project's first screen.
pub fn main_rs(project: &Project) -> Generated {
  let generator = crate::generator::for_project(project);
  let module = tailor_model::snake_case(&project.gen.module);
  let entry = project
    .docs
    .iter()
    .find(|doc| doc.kind == DocKind::Screen)
    .or_else(|| project.docs.first());
  let type_name = entry
    .map(|doc| tailor_model::pascal_case(&doc.name))
    .unwrap_or_default();
  let (width, height) = entry
    .map(|doc| (doc.canvas.width, doc.canvas.height))
    .unwrap_or((960.0, 640.0));

  let mut source = Source::new();
  source.block(comment(
    "//! ",
    &format!("{} — generated by Tailor.", project.name),
    76,
  ));
  source.line("");
  source.line(format!("mod {module};"));
  source.line("mod theme;");
  source.line("");
  source.line("use gpui::prelude::*;");
  source.line(
    "use gpui::{px, size, Application, Bounds, TitlebarOptions, WindowBounds, WindowOptions};",
  );
  source.line("");
  source.open("fn main() {");
  source.open("Application::new().run(|cx: &mut gpui::App| {");
  source.line(generator.theme_init());
  source.line("");
  source.line(format!(
    "let bounds = Bounds::centered(None, size(px({:.1}), px({:.1})), cx);",
    width, height
  ));
  source.open("cx.open_window(");
  source.open("WindowOptions {");
  source.line("window_bounds: Some(WindowBounds::Windowed(bounds)),");
  source.open("titlebar: Some(TitlebarOptions {");
  source.line(format!("title: Some(\"{}\".into()),", project.name));
  source.line("..Default::default()");
  source.close("}),");
  source.line("..Default::default()");
  source.close("},");
  if type_name.is_empty() {
    source.line("|_, cx| cx.new(|_| gpui::Empty),");
  } else {
    source.line(format!("|_, cx| cx.new({module}::{type_name}::new),"));
  }
  source.close(")");
  source.line(".unwrap();");
  source.line("cx.activate(true);");
  source.close("});");
  source.close("}");

  Generated {
    path: "main.rs".into(),
    source: source.finish(),
    notes: Vec::new(),
    lines: BTreeMap::new(),
  }
}

/// `Cargo.toml` for the exported crate.
pub fn cargo_toml(project: &Project) -> Generated {
  let name = tailor_model::snake_case(&project.name);
  let library = project.library();
  // The same requirement Tailor renders with. An export that asked for a
  // wider range could resolve to a version the canvas never drew.
  let krate = library.krate();
  let req = library.version_req();
  let source = format!(
    "[package]\n\
         name = {name:?}\n\
         version = \"0.1.0\"\n\
         edition = \"2021\"\n\
         \n\
         [dependencies]\n\
         gpui = \"0.2.2\"\n\
         {krate} = \"{req}\"\n\
         \n\
         # A smaller binary, and the recipe guise's own gallery uses.\n\
         [profile.release]\n\
         lto = \"fat\"\n\
         codegen-units = 1\n\
         panic = \"abort\"\n\
         strip = \"symbols\"\n"
  );
  Generated {
    path: "Cargo.toml".into(),
    source,
    notes: Vec::new(),
    lines: BTreeMap::new(),
  }
}

/// `theme.json` — the theme file the project carries, written back out beside
/// `theme.rs` so `include_str!` finds it. `None` when the project has none.
pub fn theme_json(project: &Project) -> Option<Generated> {
  let json = project.theme.json.trim();
  if json.is_empty() {
    return None;
  }
  Some(Generated {
    path: "theme.json".into(),
    source: format!("{json}\n"),
    notes: Vec::new(),
    lines: BTreeMap::new(),
  })
}
