//! The files that make an export a crate you can run, rather than a folder of
//! components you still have to wire up.
//!
//! `main.rs` opens a window on the first screen, `theme.rs` rebuilds the theme
//! you designed against, and `Cargo.toml` pins the same guise and gpui this
//! repo builds. Nothing here imports Tailor.

use std::collections::BTreeMap;
use tailor_model::{DocKind, Project, Scheme};

use crate::file::Generated;
use crate::rust::{comment, Source};

/// `main.rs` — a window on the project's first screen.
pub fn main_rs(project: &Project) -> Generated {
  let module = tailor_model::snake_case(&project.gen.module);
  let entry = project
    .docs
    .iter()
    .find(|doc| doc.kind == DocKind::Screen)
    .or_else(|| project.docs.first());
  let type_name = entry
    .map(|doc| tailor_model::pascal_case(&doc.name))
    .unwrap_or_default();
  let (width, height) = entry
    .map(|doc| (doc.canvas.width, doc.canvas.height))
    .unwrap_or((960.0, 640.0));

  let mut source = Source::new();
  source.block(comment(
    "//! ",
    &format!("{} — generated by Tailor.", project.name),
    76,
  ));
  source.line("");
  source.line(format!("mod {module};"));
  source.line("mod theme;");
  source.line("");
  source.line("use gpui::prelude::*;");
  source.line(
    "use gpui::{px, size, Application, Bounds, TitlebarOptions, WindowBounds, WindowOptions};",
  );
  source.line("");
  source.open("fn main() {");
  source.open("Application::new().run(|cx: &mut gpui::App| {");
  source.line("theme::build().init(cx);");
  source.line("");
  source.line(format!(
    "let bounds = Bounds::centered(None, size(px({:.1}), px({:.1})), cx);",
    width, height
  ));
  source.open("cx.open_window(");
  source.open("WindowOptions {");
  source.line("window_bounds: Some(WindowBounds::Windowed(bounds)),");
  source.open("titlebar: Some(TitlebarOptions {");
  source.line(format!("title: Some(\"{}\".into()),", project.name));
  source.line("..Default::default()");
  source.close("}),");
  source.line("..Default::default()");
  source.close("},");
  if type_name.is_empty() {
    source.line("|_, cx| cx.new(|_| gpui::Empty),");
  } else {
    source.line(format!("|_, cx| cx.new({module}::{type_name}::new),"));
  }
  source.close(")");
  source.line(".unwrap();");
  source.line("cx.activate(true);");
  source.close("});");
  source.close("}");

  Generated {
    path: "main.rs".into(),
    source: source.finish(),
    notes: Vec::new(),
    lines: BTreeMap::new(),
  }
}

/// `theme.rs` — the theme the design was laid out against.
pub fn theme_rs(project: &Project) -> Generated {
  let theme = &project.theme;
  let mut source = Source::new();
  source.block(comment(
    "//! ",
    "The theme this interface was designed against. Every component reads its \
         colours and sizes from here, so changing one value re-themes the whole app.",
    76,
  ));
  source.line("");
  source.line("use guise::prelude::*;");
  source.line("");
  source.open("pub fn build() -> Theme {");
  source.line(match theme.scheme {
    Scheme::Dark => "let mut theme = Theme::dark();",
    Scheme::Light => "let mut theme = Theme::light();",
  });
  source.line(format!("theme.primary_color = {};", theme.primary.path()));
  source.line(format!("theme.default_radius = {};", theme.radius.path()));
  source.line(format!("theme.font_family = {:?}.into();", theme.font));
  source.line("theme");
  source.close("}");

  Generated {
    path: "theme.rs".into(),
    source: source.finish(),
    notes: Vec::new(),
    lines: BTreeMap::new(),
  }
}

/// `Cargo.toml` for the exported crate.
pub fn cargo_toml(project: &Project) -> Generated {
  let name = tailor_model::snake_case(&project.name);
  let source = format!(
    "[package]\n\
         name = {name:?}\n\
         version = \"0.1.0\"\n\
         edition = \"2021\"\n\
         \n\
         [dependencies]\n\
         gpui = \"0.2.2\"\n\
         guise-ui = \"1\"\n\
         \n\
         # A smaller binary, and the recipe guise's own gallery uses.\n\
         [profile.release]\n\
         lto = \"fat\"\n\
         codegen-units = 1\n\
         panic = \"abort\"\n\
         strip = \"symbols\"\n"
  );
  Generated {
    path: "Cargo.toml".into(),
    source,
    notes: Vec::new(),
    lines: BTreeMap::new(),
  }
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn main_opens_the_first_screen() {
    let project = Project::new("Demo");
    let main = main_rs(&project);
    assert!(main.source.contains("mod ui;"));
    assert!(main.source.contains("cx.new(ui::MainScreen::new)"));
    assert!(main.source.contains("theme::build().init(cx);"));
  }

  #[test]
  fn main_falls_back_when_every_document_is_a_component() {
    let mut project = Project::new("Demo");
    project.docs[0].kind = tailor_model::DocKind::Component;
    let main = main_rs(&project);
    // Still a window: the first document stands in for the entry point.
    assert!(main.source.contains("MainScreen::new"));
  }

  #[test]
  fn the_theme_file_carries_the_project_theme() {
    let mut project = Project::new("Demo");
    project.theme.primary = tailor_model::ColorToken::Grape;
    project.theme.scheme = Scheme::Light;
    let theme = theme_rs(&project);
    assert!(theme.source.contains("Theme::light()"));
    assert!(theme
      .source
      .contains("theme.primary_color = ColorName::Grape;"));
  }

  #[test]
  fn the_manifest_names_the_project() {
    let manifest = cargo_toml(&Project::new("My App"));
    assert!(manifest.source.contains("name = \"my_app\""));
  }
}
