//! A document as a Rust file.
//!
//! Which shape it takes is decided by the document, not by a setting: anything
//! that owns state — a text field, a picker, a state variable — has to be a
//! `Render` entity, and everything else can be the `RenderOnce` builder you
//! would have written by hand.

use std::collections::{BTreeMap, BTreeSet};

use tailor_model::{DocKind, Document, Project};

use crate::expr::Hoist;
use crate::node::{entity_fields, Emitter, Owner};
use crate::rust::{comment, Source};
use crate::style::Placement;

/// One generated file.
#[derive(Debug, Clone, PartialEq)]
pub struct Generated {
  /// Relative to the export directory.
  pub path: String,
  pub source: String,
  /// Anything the user should know about what came out.
  pub notes: Vec<String>,
  /// Where each node ended up: its 1-based line in `source`. This is what
  /// turns "select this component" into "put the cursor here", which is the
  /// whole of *Open in Editor*.
  pub lines: BTreeMap<tailor_model::NodeId, usize>,
}

/// Generate the file for one document.
pub fn document(project: &Project, doc: &Document) -> Generated {
  let type_name = tailor_model::pascal_case(&doc.name);
  // `fields` is in build order; `lookup` is the same thing by id, for the
  // emitter to resolve a node to its field name.
  let library = project.library();
  let fields = entity_fields(library, doc);
  let lookup: std::collections::BTreeMap<tailor_model::NodeId, String> =
    fields.iter().cloned().collect();
  let stateful = !fields.is_empty() || !doc.state.is_empty() || !doc.actions.is_empty();
  let owner = if doc.kind == DocKind::Screen || stateful {
    Owner::Entity
  } else {
    Owner::Plain
  };

  let mut hoist = Hoist::new(library.token_paths());
  let mut emitter = Emitter::new(project, doc, &lookup, &mut hoist, owner);

  // The body first: it is what decides the imports and the hoisted colours.
  let body = emitter.emit(doc.root, Placement { absolute: false });
  let inits: Vec<String> = fields
    .iter()
    .flat_map(|(id, _)| emitter.emit_init(*id))
    .collect();
  let subscriptions = emitter.emit_subscriptions();
  let binds = emitter.binds.clone();
  let extra_imports = emitter.imports.clone();
  let mut notes = emitter.notes.clone();

  if doc.kind == DocKind::Component && stateful {
    notes.push(format!(
      "{} holds state, so it generates as a Render entity rather than a RenderOnce builder",
      doc.name
    ));
  }

  let hoisted = hoist.lines();
  let mut source = Source::new();

  source.block(comment(
    "//! ",
    &format!(
      "{} — generated by Tailor from {}. Edit the design and regenerate, \
             or take this file and own it; it has no dependency on Tailor.",
      type_name, project.name
    ),
    76,
  ));
  source.line("");
  // The library's prelude, then the gpui items this particular file reached
  // for. The prelude is the provider's to name — everything below it is not.
  for line in library.prelude() {
    source.line(*line);
    if line.starts_with("use gpui::prelude") {
      source.line(gpui_imports(
        &body,
        &inits,
        &hoisted,
        owner,
        !fields.is_empty(),
      ));
    }
  }
  for import in &extra_imports {
    source.line(import);
  }
  source.blank();

  if owner == Owner::Plain {
    source.line("#[derive(IntoElement, Default)]");
  }
  if fields.is_empty() && doc.state.is_empty() {
    source.line(format!("pub struct {type_name};"));
  } else {
    source.open(format!("pub struct {type_name} {{"));
    for (id, field) in &fields {
      let rust = doc
        .node(*id)
        .and_then(|node| library.get(&node.kind))
        .map(|spec| spec.rust)
        .unwrap_or("()");
      // Public like the state signals: these handles are how the host
      // reads a field's value or drives it later.
      source.line(format!("pub {field}: Entity<{rust}>,"));
    }
    for var in &doc.state {
      source.line(format!(
        "pub {}: Signal<{}>,",
        tailor_model::snake_case(&var.name),
        var.ty.rust()
      ));
    }
    source.close("}");
  }
  source.blank();

  source.open(format!("impl {type_name} {{"));
  match owner {
    Owner::Entity => {
      // A screen with no fields and no state still has to take a context
      // — `cx.new(Screen::new)` requires the shape — but naming it would
      // warn on the first build.
      let builds_something =
        !inits.is_empty() || !subscriptions.is_empty() || !doc.state.is_empty();
      let param = if builds_something { "cx" } else { "_cx" };
      source.open(format!(
        "pub fn new({param}: &mut Context<Self>) -> Self {{"
      ));
      // State first, as locals. A field that reads a signal reads it
      // while building — there is no `self` yet — and a two-way binding
      // needs both sides to exist before it can be made.
      for var in &doc.state {
        source.line(format!(
          "let {} = {};",
          tailor_model::snake_case(&var.name),
          var.initializer()
        ));
      }
      source.block(inits.clone());
      for line in &binds {
        source.line(line);
      }
      for line in &subscriptions {
        source.line(line);
      }
      if fields.is_empty() && doc.state.is_empty() {
        source.line(&type_name);
      } else {
        source.open(format!("{type_name} {{"));
        for (_, field) in &fields {
          source.line(format!("{field},"));
        }
        for var in &doc.state {
          source.line(format!("{},", tailor_model::snake_case(&var.name)));
        }
        source.close("}");
      }
      source.close("}");
      for action in &doc.actions {
        source.blank();
        if !action.note.is_empty() {
          source.block(comment("/// ", &action.note, 72));
        }
        source.open(format!(
          "pub fn {}(&mut self, cx: &mut Context<Self>) {{",
          tailor_model::snake_case(&action.name)
        ));
        if action.body.trim().is_empty() {
          source.line("// TODO");
          source.line("let _ = cx;");
        } else {
          for line in action.body.lines() {
            source.line(line);
          }
        }
        source.close("}");
      }
    }
    Owner::Plain => {
      source.open("pub fn new() -> Self {");
      source.line(&type_name);
      source.close("}");
    }
  }
  source.close("}");
  source.blank();

  let uses_cx = hoisted
    .iter()
    .chain(body.iter())
    .any(|line| mentions(line, "cx"));
  let cx_name = if uses_cx { "cx" } else { "_cx" };
  match owner {
    Owner::Entity => {
      source.open(format!("impl Render for {type_name} {{"));
      source.open(format!(
                "fn render(&mut self, _window: &mut Window, {cx_name}: &mut Context<Self>) -> impl IntoElement {{"
            ));
    }
    Owner::Plain => {
      source.open(format!("impl RenderOnce for {type_name} {{"));
      source.open(format!(
        "fn render(self, _window: &mut Window, {cx_name}: &mut App) -> impl IntoElement {{"
      ));
    }
  }
  source.block(hoisted);
  if !body.is_empty() {
    source.block(body.clone());
  }
  source.close("}");
  source.close("}");

  let (source, lines) = strip_marks(source.finish());

  Generated {
    path: format!("{}.rs", tailor_model::snake_case(&doc.name)),
    source,
    notes,
    lines,
  }
}

/// Take the node tags back out, learning each node's line on the way. A tag
/// sits on its own line, so the line it is removed from is the line its
/// expression now starts on — and every later tag shifts up by the number of
/// tags already gone.
fn strip_marks(source: String) -> (String, BTreeMap<tailor_model::NodeId, usize>) {
  let mut lines = BTreeMap::new();
  let mut out = String::with_capacity(source.len());
  let mut number = 0usize;

  for line in source.lines() {
    match line.trim_start().strip_prefix(crate::node::MARK) {
      Some(id) => {
        if let Ok(id) = id.trim().parse::<u32>() {
          // The expression is whatever comes next, which will be
          // written as the line after the ones already kept.
          lines.insert(tailor_model::NodeId(id), number + 1);
        }
      }
      None => {
        out.push_str(line);
        out.push('\n');
        number += 1;
      }
    }
  }
  (out, lines)
}

/// Does the line use this identifier as a word, rather than inside a string or
/// a longer name?
fn mentions(line: &str, needle: &str) -> bool {
  let bytes = line.as_bytes();
  let mut start = 0;
  while let Some(found) = line[start..].find(needle) {
    let at = start + found;
    let before_ok = at == 0 || !is_ident(bytes[at - 1]);
    let after = at + needle.len();
    let after_ok = after >= bytes.len() || !is_ident(bytes[after]);
    if before_ok && after_ok {
      return true;
    }
    start = at + needle.len();
  }
  false
}

fn is_ident(byte: u8) -> bool {
  byte.is_ascii_alphanumeric() || byte == b'_'
}

/// The named gpui import, filtered to what the file actually uses. Unused
/// imports are only a warning, but a generated file that warns on the first
/// build reads as sloppy.
fn gpui_imports(
  body: &[String],
  inits: &[String],
  hoisted: &[String],
  owner: Owner,
  has_entities: bool,
) -> String {
  let all: Vec<String> = body
    .iter()
    .chain(inits.iter())
    .chain(hoisted.iter())
    .cloned()
    .collect();
  let used = |needle: &str| all.iter().any(|line| mentions(line, needle));

  let mut names: BTreeSet<&str> = BTreeSet::new();
  names.insert("Window");
  if owner == Owner::Plain {
    names.insert("App");
  }
  if has_entities {
    names.insert("Entity");
  }
  if used("div") {
    names.insert("div");
  }
  if used("px") {
    names.insert("px");
  }
  if used("FontWeight") {
    names.insert("FontWeight");
  }
  format!(
    "use gpui::{{{}}};",
    names.into_iter().collect::<Vec<_>>().join(", ")
  )
}

/// The `mod.rs` that ties the generated components together.
pub fn module(project: &Project) -> Generated {
  let mut source = Source::new();
  source.block(comment(
    "//! ",
    &format!("The {} interface, generated by Tailor.", project.name),
    76,
  ));
  source.line("");
  for doc in &project.docs {
    let module = tailor_model::snake_case(&doc.name);
    source.line(format!("mod {module};"));
  }
  source.line("");
  for doc in &project.docs {
    let module = tailor_model::snake_case(&doc.name);
    source.line(format!(
      "pub use {module}::{};",
      tailor_model::pascal_case(&doc.name)
    ));
  }
  Generated {
    path: "mod.rs".into(),
    source: source.finish(),
    notes: Vec::new(),
    lines: BTreeMap::new(),
  }
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn identifiers_are_matched_as_whole_words() {
    assert!(mentions("let x = cx;", "cx"));
    assert!(!mentions("let context = 1;", "cx"));
    assert!(!mentions("\"prefix\"", "px"));
    assert!(mentions(".p(px(8.))", "px"));
  }
}
